version: '2'
services:
  config-service:
    image: dockerhackathon/michackathon-config
    ports:
     - 8888:8888
    environment:
     - CONFIGURATION_REPOSITORY=https://github.com/johntomcy/michackathon-configuration.git
     - CONFIGURATION_BRANCH=master
  ui-service:
    image: dockerhackathon/michackathon-ui
    ports:
     - 8080:8080
    depends_on:
     - discovery-service
     - auth-service
     - user-api-service
     - gateway-service
    links:
     - discovery-service
     - gateway-service
     - auth-service
     - user-api-service
     - config-service
    entrypoint: ./wait-for-service.sh http://discovery-service:8081/health -- java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
  discovery-service:
    image: dockerhackathon/michackathon-discovery
    ports:
     - 8081:8081
    depends_on:
     - config-service
    links:
     - config-service
    entrypoint: ./wait-for-service.sh http://config-service:8888/health -- java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
  auth-service:
    image: dockerhackathon/michackathon-auth
    ports:
     - 8082:8082
    depends_on:
     - discovery-service
    links:
     - discovery-service
     - config-service
    entrypoint: ./wait-for-service.sh http://discovery-service:8081/health -- java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
  gateway-service:
    image: dockerhackathon/michackathon-gateway
    ports:
      - 8100:8100
    depends_on:
      - discovery-service
    links:
      - discovery-service
      - auth-service
      - user-api-service
      - config-service
    entrypoint: ./wait-for-service.sh http://discovery-service:8081/health -- java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
  user-api-service:
    image: dockerhackathon/michackathon-user-api
    ports:
     - 8101:8101
    depends_on:
     - discovery-service
     - db-users
     - elasticsearch
     - logstash
     - kibana
     - curator
    links:
     - discovery-service
     - auth-service
     - config-service
     - db-users
    entrypoint: ./wait-for-it.sh db-users:5432 -- ./wait-for-service.sh http://discovery-service:8081/health -- java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
  admin-service:
    image: dockerhackathon/michackathon-admin
    ports:
      - 8777:8777
    depends_on:
      - discovery-service
    links:
      - discovery-service
      - auth-service
      - user-api-service
      - ui-service
      - config-service
    entrypoint: ./wait-for-service.sh http://discovery-service:8081/health -- java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
  hystrix-dashboard-service:
    image: dockerhackathon/michackathon-hystrix-dashboard
    ports:
     - 8383:8383
    depends_on:
     - discovery-service
     - config-service
    links:
     - discovery-service
     - config-service
    entrypoint: ./wait-for-service.sh http://discovery-service:8081/health -- java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
  turbine-service:
    image: dockerhackathon/michackathon-turbine
    ports:
     - 8989:8989
    depends_on:
     - discovery-service
     - config-service
    links:
     - discovery-service
     - config-service
    entrypoint: ./wait-for-service.sh http://discovery-service:8081/health -- java -Djava.security.egd=file:/dev/./urandom -jar /app.jar

  db-users:
    image: postgres:9.6.0
    ports:
      - 6001:5432
    environment:
     - POSTGRES_DB=db_users
     - POSTGRES_USER=db_users_user
     - POSTGRES_PASSWORD=db_users_password
     - PGDATA=/var/lib/postgresql/data/pgdata
  db-couch:
    image: couchbase:community
    ports:
      - 8091-8094:8091-8094
      - 11210:11210
  travel-history-api-service:
      image: dockerhackathon/michackathon-travel-history-api
      ports:
       - 8102:8102
      depends_on:
       - discovery-service
       - db-couch
      links:
       - discovery-service
       - auth-service
       - config-service
      entrypoint: ./wait-for-it.sh db-couch:8091 -- ./wait-for-service.sh http://discovery-service:8081/health -- java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
  recommendation-api-service:
        image: dockerhackathon/michackathon-recommendation-api
        ports:
         - 8103:8103
        depends_on:
         - discovery-service
         - db-couch
        links:
         - discovery-service
         - auth-service
         - config-service
        entrypoint: ./wait-for-it.sh db-couch:8091 -- ./wait-for-service.sh http://discovery-service:8081/health -- java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
  flight-api-service:
        image: dockerhackathon/michackathon-flight-api
        ports:
         - 8104:8104
        depends_on:
         - discovery-service
         - db-couch
        links:
         - discovery-service
         - auth-service
         - config-service
        entrypoint: ./wait-for-it.sh db-couch:8091 -- ./wait-for-service.sh http://discovery-service:8081/health -- java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
  elasticsearch:
      image: elasticsearch:2.2
      restart: always
      ports:
          - 9200:9200
          - 9300:9300
      volumes:
          - ./michackathon-elasticsearch/data:/usr/share/michackathon-elasticsearch/data
  logstash:
      build: michackathon-logstash
      restart: always
      command: logstash -f /config-dir/logstash.conf
      ports:
        - 5044:5044
      depends_on:
        - elasticsearch
      links:
        - elasticsearch
  kibana:
      image: kibana:4.4
      restart: always
      ports:
        - 5601:5601
      depends_on:
        - elasticsearch
      links:
        - elasticsearch
  curator:
      build: michackathon-curator
      restart: always
      depends_on:
        - elasticsearch
      links:
        - elasticsearch
  # rabbitmq:
  #     image: rabbitmq:3.6.5
  #     restart: always
  #     ports:
  #       - 15672:15672
  node-service:
      build: michackathon-node-service
      restart: always
      ports:
        - 3000:3000
  node-sidecar-service:
    image: dockerhackathon/michackathon-node-sidecar
    restart: always
    ports:
     - 8741
    depends_on:
     - discovery-service
     - config-service
     - node-service
    links:
     - discovery-service
     - node-service
     - config-service
    entrypoint: ./wait-for-service.sh http://discovery-service:8081/health -- java -Djava.security.egd=file:/dev/./urandom -jar /app.jar
